# List of layers to include in the build
# Paths should be relative to the build directory or absolute
../sources/meta-playground/meta-playground-os
../sources/meta-playground/meta-playground-bsp
../sources/meta-openembedded/meta-oe
../sources/meta-ollama
