# Include a base machine configuration
include conf/machine/qemux86-64.conf

# Preferred kernel
PREFERRED_PROVIDER_virtual/kernel = "linux-playground"

# added to the override system, allowing recipes and .bbappend files to apply
# modifications specifically for this machine.
MACHINEOVERRIDES =. "playground-x86:"
